### PR TITLE
[SSLNTV-18] Add RHEL9 Support

### PR DESCRIPTION
**Pull request by ettoreleandrotognoli**
Issue: [SSLNTV-18](https://issues.redhat.com/browse/SSLNTV-18)

### CODE REVIEW

**Comment by fjuma** [comment]
@ettoreleandrotognoli Thanks for working on this, it looks good to me! Have you been able to try this out on RHEL 9?

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
@ettoreleandrotognoli It would be good to run the WildFly OpenSSL tests to make sure that passes with this build. To do that, you'll need the master branch from https://github.com/wildfly-security/wildfly-openssl. Then you'll want to update this line to use your SNAPSHOT version of `wildfly-openssl-natives`:

https://github.com/wildfly-security/wildfly-openssl/blob/7e92d61173ce04bbf7768ee64b80a910e8fff517/java/pom.xml#L291

You can then build `wildfly-openssl` using `mvn clean install -Djboss.modules.os-name=linux-rhel9`.

**Comment by ettoreleandrotognoli** [comment]
@fjuma done
The tests looks ok ^^

**Comment by fjuma** [comment]
Great, thanks @ettoreleandrotognoli!

**Pull request merged**
