### PR TITLE
[SSLNTV-38] Match function headers with the prototype

### PR DESCRIPTION
**Pull request by stormqueen1990**
Fixes: #28

Update the function declarations to match their corresponding prototypes.

https://issues.redhat.com/browse/SSLNTV-38

### CODE REVIEW

**Comment by fjuma** [comment]
@stormqueen1990 Thank you very much for creating the issue and submitting a PR! Just to let you know, we'll take a closer look at this PR this week. We are in the process of updating our CI runs so we will hopefully be able to re-trigger the tests on this one with MacOS, Ubuntu, and Windows soon.

**Comment by stormqueen1990** [comment]
Hi there, @fjuma! Thanks for the update!

**Comment by fjuma** [comment]
@stormqueen1990 We've now updated our GitHub Actions CI jobs (https://github.com/wildfly-security/wildfly-openssl-natives/pull/31). Whenever you get a chance, would you be able to rebase this PR? That should trigger the new CI runs.

If you could also update the commit message to reference [SSLNTV-38](https://issues.redhat.com/browse/SSLNTV-38), that would be great. (We currently use JIRA as our issue tracker so I created to SSLNTV-38 to track this fix.)

Thanks!

**Comment by stormqueen1990** [comment]
> @stormqueen1990 We've now updated our GitHub Actions CI jobs (#31). Whenever you get a chance, would you be able to rebase this PR? That should trigger the new CI runs.
> 
> If you could also update the commit message to reference [SSLNTV-38](https://issues.redhat.com/browse/SSLNTV-38), that would be great. (We currently use JIRA as our issue tracker so I created to SSLNTV-38 to track this fix.)
> 
> Thanks!

Hi there, @fjuma! I just updated the commit message and rebased this branch. Sorry for the delay!

**Comment by fjuma** [comment]
Thank you very much @stormqueen1990, looks good!

**Review by fjuma — APPROVED** [review]

**Comment by fjuma** [comment]
@Skyllarr Please review as well.

**Review by Skyllarr — APPROVED** [review]

**Comment by Skyllarr** [comment]
@stormqueen1990 Thank you!

**Pull request merged**
